[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "nbopen"
author = "Thomas Kluyver"
author-email = "thomas@kluyver.me.uk"
home-page = "https://github.com/takluyver/nbopen"
description-file = "README.rst"
requires = [
    "notebook",
    "nbformat",
    "timeout_decorator"
]
requires-python = ">=3.5"
classifiers = [
    "License :: OSI Approved :: BSD License", "Programming Language :: Python :: 3",
    "Framework :: Jupyter",
]


[tool.flit.scripts]
nbopen = "nbopen:main"
