#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from setuptools import setup, find_packages

setup(
    name="nbopen",
    version="0.6",
    description='Open a notebook from the command line in the best available server',
    author='Thomas Kluyver',
    author_email='thomas@kluyver.me.uk',
    url='https://github.com/takluyver/nbopen',
    packages=find_packages(),
    install_requires=[],
    extras_require={"develop": []},
    entry_points={
        "console_scripts": [
            "nbopen = nbopen:main"
        ],
        "gui_scripts": []
    }
)
